name: lambda-calculus
version: 0.1.0.0
synopsis: Lambda Calculus implementation in Haskell
description: See the report
maintainer: Floris Westerman
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - containers

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - lambda-calculus

tests:
  lambda_tests:
    main: lambda_tests.lhs
    source-dirs: test
    dependencies:
      - lambda-calculus
      - QuickCheck
      - hspec
      - containers
