name: lambda-calculus
version: 0.1.0.0
synopsis: Lambda Calculus implementation in Haskell
description: See the report
maintainer: Floris Westerman
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - containers

library:
  source-dirs: lib

tests:
  UntypedLambdaTests:
    main: UntypedLambdaTests.lhs
    source-dirs: test
    dependencies:
      - QuickCheck
      - hspec
      - containers
      - lambda-calculus
